### ISSUE TITLE
the wall can be drawn on source as well as target

### ISSUE THREAD

**Issue by rush181200** [abhijeetSinghRajput/path-finder-YourTube-tutorial#1]
// to solve add this
 if(isDrawing && !e.target.classList.contains('source') && !e.target.classList.contains('target') ){
            e.target.classList.add('wall');
        }

**Comment by abhijeetSinghRajput** [comment]
Fix(board interaction): Sure, here's a professional commit message for ensuring that walls are not drawn on 'source' or 'target' elements:

**Comment by abhijeetSinghRajput** [comment]
> // to solve add this
>  if(isDrawing && !e.target.classList.contains('source') && !e.target.classList.contains('target') ){
>             e.target.classList.add('wall');
>         }

Hi Rushabh,

Thank you for bringing this issue to our attention and providing the solution! Your contribution helps ensure that walls are not drawn on 'source' or 'target' elements, which is crucial for maintaining the functionality of our pathfinding algorithm.

If you're interested in working together on other projects, please let me know, and we can discuss the details further.

**Comment by abhijeetSinghRajput** [comment]
Fix(board interaction):  ensuring that walls are not drawn on 'source' or 'target' elements:
